### ISSUE TITLE
As a user want to start a game, I want to select the area of cities that will appear in the game, so I can narrow down the guessed city range.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Client#35]
### Acceptance Criteria
- [x]  I can click on the city category I want from the drop-down bar on the game lobby page
- [x]  Upon successfully choosing a city category, the chosen category will be shown inside of the drop down menu

### Development Tasks
- [x] sopra-fs23-group-32/SoPra23_Client#15
- [x] sopra-fs23-group-32/SoPra23_Server#80
- [x] sopra-fs23-group-32/SoPra23_Server#103
- [x] sopra-fs23-group-32/SoPra23_Server#114
