### ISSUE TITLE
As a user, I want to join a Multiplayer game

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Client#83]
### Acceptance Criteria
- [x] From the game lobby, I want to be able to select "Join Game" which will take me to the joinGame screen
- [x] From the joinGame screen, I want to find different open lobbys, from which I can join one by pressing on "join"
- [x] After pressing on it, I am in the lobby I wanted to join

### Development Tasks

- [x]  sopra-fs23-group-32/SoPra23_Server#64
- [x] sopra-fs23-group-32/SoPra23_Client#73
- [x] sopra-fs23-group-32/SoPra23_Client#66
